### ISSUE TITLE
Merge instance-based changes from perwendel/spark#308

### ISSUE THREAD

**Issue by heuermh** [heuermh/sparkling#12]
See perwendel/spark pull request #308.

**Comment by heuermh** [comment]
@ggalmazor @jkwatson @benhyland @borud @ribomation @i386 I created this hard fork of perwendel/spark a while back for other reasons.  If you need a place to land the instance-based changes, please feel free to pull request here and I'll release to Maven Central.  Or if someone else wants to hard fork to a different project name & Maven coordinates, I would support that.

**Comment by jkwatson** [comment]
@heuermh I'm interested in what your goals are for sparkling. And, how you intend to manage the projects & PRs.

**Comment by ggalmazor** [comment]
This is great and I'm very glad that someone will benefit for this changes I made... Honestly it's only some basic work to patch this static API but imho there are lots of improvements that ought to be made to the library as a whole. Especially now that we've the experience of using Spark in big apps for some years now.

I will continue using Spark/Sparkling in my projects but right now I'm more interested on developing a new generation of lightweight web libraries that harness all the features of modern Java8. If you're interested, take a look at http://github.com/ggalmazor/jfry (sorry for the spam)

**Comment by heuermh** [comment]
@jkwatson I don't have any explicit goals at the moment, other than an interest in landing the instance-based changes somewhere.

Merging them here would require search and replace spark &rarr; sparkling and also consideration on whether to move forward first, to grab the JDK8-related changes upstream, for example.

A new domain name, maven groupId, and a github organization might help attract interest.

@ggalmazor jfry does look interesting, thank you.  What would you like to do with your patch now that the pull request has been closed?

**Comment by ggalmazor** [comment]
@heuermh My PR was a very simple patch to get an instance AP and I've deleted it now that we have https://github.com/perwendel/spark/pull/344 

I think that that set of changes are better suited and will have more continuity of they're merged into Sparkling. Then you only need to make some small changes to make [SparkInstance](https://github.com/perwendel/spark/blob/master/src/main/java/spark/SparkInstance.java) public.

**Comment by heuermh** [comment]
Closing as WontFix
